apiVersion: apps/v1
kind: Deployment
metadata:
  name: sv-worker
spec:
  selector:
    matchLabels:
      app: sv-worker
  replicas: 2
  template:
    metadata:
      labels:
        app: sv-worker
    spec:
      containers:
        - name: sv-worker
          image: sv-worker
