apiVersion: kustomize.config.k8s.io/v1beta1
resources:
  - node-apps/sv-main/deployment.yaml
  - node-apps/sv-main/service.yaml
  - node-apps/sv-worker/deployment.yaml
images:
  - name: sv-main
    newName: karangauswami/sv-main
    newTag: '663996bc331b3f62b6db205e201f95f5cf18fad3'
  - name: sv-worker
    newName: karangauswami/sv-worker
    newTag: '663996bc331b3f62b6db205e201f95f5cf18fad3'
