apiVersion: apps/v1
kind: Deployment
metadata:
  name: sv-main
spec:
  selector:
    matchLabels:
      app: sv-main
  replicas: 1
  template:
    metadata:
      labels:
        app: sv-main
    spec:
      containers:
        - name: sv-main
          image: karangauswami/sv-main:latest
          ports:
            - containerPort: 3000
